export const COM_SET_MENU = 'COM_SET_MENU'

// HOME
export const HOME_SET_CENTER_APP_LIST = 'HOME_SET_CENTER_APP_LIST'
export const HOME_SET_LOCAL_APP_LIST = 'HOME_SET_LOCAL_APP_LIST'

// LIST
export const LIST_SET_MENU = 'LIST_SET_MENU'
export const LIST_SET_TITLE = 'LIST_SET_TITLE'
export const LIST_SET_NEWS = 'LIST_SET_NEWS'
